using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject: Lightweight dependency injection for .NET")]
[assembly: AssemblyCompanyAttribute("bbv Software Services Ag")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2010 bbv Software Services Ag and contributors")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

